baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "cross cluster network connectivity for Kubernetes"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/submariner-io/website/edit/master/src/content/"
  description = "Documentation website for the submariner project"
  author = "The submariner community"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Submariner k8s project documentation website"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/submariner-io/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope'></i> User mailing list"
url = "https://bit.ly/submariner-users"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope'></i> Devel mailing list"
url = "https://bit.ly/submariner-dev"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-video'></i> Youtube demos"
url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Google Calendar"
identifier = "gcal"
url = "https://calendar.google.com/calendar?cid=NHFuZGVoOGY0bzZ1ajlvZnBsczh1NWNlZ2tAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ"
weight = 60

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/submarinerio"
weight = 50

[Languages.es]
title = "Proyecto Submariner, documentaci√≥n"
weight = 2
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/submariner-io/"
weight = 10


[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope'></i>Lista de correo (usuarios)"
url = "https://bit.ly/submariner-users"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope'></i>Lista de correo (desarrolladores)"
url = "https://bit.ly/submariner-dev"
weight = 30

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-video'></i> Demos youtube"
url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
weight = 40

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/submarinerio"
weight = 50

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Google Calendar"
identifier = "gcal"
url = "https://calendar.google.com/calendar?cid=NHFuZGVoOGY0bzZ1ajlvZnBsczh1NWNlZ2tAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ"
weight = 60
