---
name: check-pr

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make the static files
        run: make static

      - uses: actions/upload-artifact@v1
        with:
          name: static-website
          path: output
