---
name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create secret key to git push
        run: |
          echo '=================== Create deploy key to push ==================='
          set -x
          mkdir $HOME/.ssh
          ssh-keyscan -t rsa github.com > $HOME/.ssh/known_hosts
          echo "${GIT_DEPLOY_KEY}" > $HOME/.ssh/id_rsa
          chmod 400 $HOME/.ssh/id_rsa
          git config --global user.email "submariner@website-ci"
          git config --global user.name "Submariner Website CI"
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Build the website static files
        run: make static

      - name: Push the updated static files
        run: ./scripts/publish
